---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - bmc.tinkerbell.org
  resources:
  - jobs
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - cluster.x-k8s.io
  resources:
  - clusters
  - clusters/status
  - machines
  - machines/status
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - tinkerbellclusters
  - tinkerbellmachines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - tinkerbellclusters/status
  - tinkerbellmachines/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - tinkerbell.org
  resources:
  - hardware
  - hardware/status
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tinkerbell.org
  resources:
  - templates
  - templates/status
  - workflows
  - workflows/status
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
