# amd64 (x86-64) drop-in: BIOS + EFI dual-boot.
# Adds the BIOS boot partition via the mkosi.repart.amd64/ overlay dir and
# installs the BIOS bootloader alongside the EFI one.

[Match]
Architecture=x86-64

[Output]
RepartDirectories=mkosi.repart
RepartDirectories=mkosi.repart.amd64

[Content]
BiosBootloader=grub
Packages=
        grub-efi-amd64-bin
        grub-efi-amd64-signed
        grub-pc-bin
        shim-signed
